//! Private staged next-start target section: start-up overlay and atomic persistence.
use std::{
    fs::{self, File, OpenOptions},
    io::{self, Read, Write},
    os::unix::fs::OpenOptionsExt,
    path::Path,
};

use serde::{Deserialize, Serialize};

use super::{ConfigurationLoadError, FileConfiguration, TargetEntry, targets::TargetSection};

const STAGED_FORMAT: u32 = 1;
const MAX_STAGED_BYTES: u64 = 256 * 1024;

/// Private next-start target section written by an API apply.
#[derive(Deserialize, Serialize)]
#[serde(deny_unknown_fields)]
struct StagedTargets {
    format: u32,
    /// Digest of the startup file's own target section this overlay replaces.
    base_digest: String,
    applied_by: String,
    applied_at: String,
    target_id: String,
    #[serde(default)]
    targets: Vec<TargetEntry>,
}

/// Replaces the loaded target section with a matching staged overlay, if one exists.
pub(super) fn overlay(configuration: &mut FileConfiguration) -> Result<(), ConfigurationLoadError> {
    let Some(path) = configuration.configuration_api.staged_targets_file() else {
        return Ok(());
    };
    let base = TargetSection::of(configuration);
    if let Some(staged) = read(path, &base)? {
        configuration.bridge.target_id = staged.target_id;
        configuration.targets = staged.targets;
    }
    Ok(())
}

pub(super) fn read(
    path: &Path,
    base: &TargetSection,
) -> Result<Option<TargetSection>, ConfigurationLoadError> {
    let file = match File::open(path) {
        Ok(file) => file,
        Err(error) if error.kind() == io::ErrorKind::NotFound => return Ok(None),
        Err(_) => return Err(ConfigurationLoadError::Unavailable),
    };
    let mut document = String::new();
    file.take(MAX_STAGED_BYTES + 1)
        .read_to_string(&mut document)
        .map_err(|_| ConfigurationLoadError::InvalidStagedTargets)?;
    if document.len() as u64 > MAX_STAGED_BYTES {
        return Err(ConfigurationLoadError::InvalidStagedTargets);
    }
    let staged: StagedTargets =
        toml::from_str(&document).map_err(|_| ConfigurationLoadError::InvalidStagedTargets)?;
    if staged.format != STAGED_FORMAT {
        return Err(ConfigurationLoadError::InvalidStagedTargets);
    }
    // An operator edited the startup file's target section after the API apply: neither side
    // silently wins. Remove the staged file or re-apply to resolve it.
    if staged.base_digest != base.digest() {
        return Err(ConfigurationLoadError::StagedTargetsConflict);
    }
    Ok(Some(TargetSection {
        target_id: Some(staged.target_id),
        targets: staged.targets,
    }))
}

pub(super) fn write(
    path: &Path,
    base_digest: &str,
    section: &TargetSection,
    actor: &str,
    applied_at: &str,
) -> io::Result<()> {
    let staged = StagedTargets {
        format: STAGED_FORMAT,
        base_digest: base_digest.to_owned(),
        applied_by: actor.to_owned(),
        applied_at: applied_at.to_owned(),
        target_id: section.target_id.clone().unwrap_or_default(),
        targets: section.targets.clone(),
    };
    let encoded = toml::to_string(&staged).map_err(io::Error::other)?;
    write_atomically(
        path,
        &format!(
            "# Generated by the management configuration API; loaded on the next start.\n\
             # Delete this file to return to the startup file's target section.\n{encoded}"
        ),
    )
}

/// Returns to the startup file's own target section.
pub(super) fn remove(path: &Path) -> io::Result<()> {
    match fs::remove_file(path) {
        Ok(()) => sync_parent(path),
        Err(error) if error.kind() == io::ErrorKind::NotFound => Ok(()),
        Err(error) => Err(error),
    }
}

fn write_atomically(path: &Path, contents: &str) -> io::Result<()> {
    let directory = path
        .parent()
        .filter(|parent| !parent.as_os_str().is_empty())
        .ok_or_else(|| io::Error::other("staged target path has no directory"))?;
    let name = path
        .file_name()
        .ok_or_else(|| io::Error::other("staged target path has no file name"))?;
    let temporary = directory.join(format!(
        ".{}.{}.tmp",
        name.to_string_lossy(),
        std::process::id()
    ));
    let result = (|| {
        // A crash between create and rename leaves this private file behind; never let it block
        // every later apply.
        match fs::remove_file(&temporary) {
            Err(error) if error.kind() != io::ErrorKind::NotFound => return Err(error),
            _ => {}
        }
        let mut file = OpenOptions::new()
            .write(true)
            .create_new(true)
            .mode(0o600)
            .open(&temporary)?;
        file.write_all(contents.as_bytes())?;
        file.sync_all()?;
        fs::rename(&temporary, path)?;
        sync_parent(path)
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temporary);
    }
    result
}

fn sync_parent(path: &Path) -> io::Result<()> {
    match path.parent() {
        Some(parent) if !parent.as_os_str().is_empty() => File::open(parent)?.sync_all(),
        _ => Ok(()),
    }
}
