// Keep a compact, local-only validation schema in the browser bundle.
import { readFileSync, writeFileSync } from 'node:fs';
const inputs = [
  '../../adapters/management/schemas/capture-line-v1.schema.json',
  '../../crates/contracts/schemas/v1.0/service-identity.schema.json',
  '../../crates/contracts/schemas/v1.0/trace-record.schema.json',
];
const annotations = new Set(['description', 'title', '$schema', 'x-uob-contract-version']);
const supported = new Set(['$id', '$defs', '$ref', 'type', 'properties', 'required', 'additionalProperties',
  'oneOf', 'anyOf', 'const', 'enum', 'format', 'pattern', 'minimum', 'maximum', 'minLength']);
function compact(schema) {
  if (typeof schema === 'boolean') return schema;
  return Object.fromEntries(Object.entries(schema).filter(([key]) => !annotations.has(key)).map(([key, value]) => {
    if (!supported.has(key)) throw new Error(`Unsupported schema keyword: ${key}`);
    if (key === 'properties' || key === '$defs') value = Object.fromEntries(Object.entries(value).map(([name, child]) => [name, compact(child)]));
    if (key === 'oneOf' || key === 'anyOf') value = value.map(compact);
    if (key === 'additionalProperties') value = compact(value);
    return [key, value];
  }));
}
const schemas = inputs.map(path => compact(JSON.parse(readFileSync(new URL(path, import.meta.url), 'utf8'))));
const output = '// Generated by scripts/capture-schema.mjs; do not edit.\nexport const captureSchemas = ' + JSON.stringify(schemas) + ';\n';
const destination = new URL('../src/debug/capture-schemas.ts', import.meta.url);
if (process.argv.includes('--check')) {
  if (readFileSync(destination, 'utf8') !== output) throw new Error('Capture schemas changed; run node scripts/capture-schema.mjs');
} else writeFileSync(destination, output);
